# workflow

name: Run_Pipeline

on: 
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: covidresources   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'covid19-resources/*'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: windows-latest
    environment: dev
    
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_05ff50a9a9fd4cb38dc1e49ff85ef244 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
    - name: Sign out of Azure
      run: |
        az logout
